// AUTO-GENERATED by scripts/generate-cache-seed.ts — 손으로 편집하지 말 것.
// 프롬프트 버전 바뀌면 재생성: npm run seed:cache
// 생성 버전: meaning-v2.15-abstract-seq · 항목 3/33
import type { JudgeCacheSeed } from './geminiJudge';

export const CACHE_SEED: JudgeCacheSeed = {
  "version": "meaning-v2.15-abstract-seq",
  "schema": 2,
  "entries": {
    "서리 칼날로 적을 벤다": {
      "schema_version": 2,
      "disposition": "cast",
      "spell": {
        "name": "서리 칼날",
        "effect": "damage",
        "target": "enemy",
        "element_primary": "ice",
        "element_secondary": null,
        "form": "slash",
        "size": "medium",
        "speed": "normal",
        "status": [
          "freeze"
        ],
        "power": 65,
        "cost": 39,
        "flavor": "차가운 얼음 칼날로 적을 가른다"
      }
    },
    "분신을 만들어서 지그재그로 돌진시켜라": {
      "schema_version": 2,
      "disposition": "cast",
      "spell": {
        "name": "분신 돌진",
        "effect": "summon",
        "target": "area",
        "element_primary": "light",
        "element_secondary": null,
        "form": "summon",
        "size": "medium",
        "speed": "normal",
        "status": [],
        "power": 65,
        "cost": 35,
        "flavor": "빛의 분신이 궤도를 그리며 적에게 향한다",
        "behavior": {
          "steps": [
            {
              "kind": "zigzag",
              "seconds": 2,
              "speed": 250,
              "amplitude": 50
            },
            {
              "kind": "dash",
              "seconds": 1,
              "speed": 400
            }
          ],
          "loop": false
        }
      }
    },
    "사방의 포화": {
      "schema_version": 2,
      "disposition": "cast",
      "spell": {
        "name": "사방의 포화",
        "effect": "damage",
        "target": "area",
        "element_primary": "fire",
        "element_secondary": "light",
        "form": "nova",
        "size": "huge",
        "speed": "fast",
        "status": [
          "burn"
        ],
        "power": 85,
        "cost": 51,
        "flavor": "사방에서 쏟아지는 눈부신 화염의 세례",
        "shape": {
          "kind": "ring",
          "amplitude": 80
        }
      }
    }
  }
};
