/**
 * 캐시 프리워밍 시드 생성기 (③, #158) — 시연 코퍼스를 라이브 워커로 사전 판정해
 * `src/spell/cacheSeed.generated.ts`를 만든다. 심사위원 첫 영창이 0ms로 나가고,
 * 라이브 호출이 줄어 할당량(RPD) 압박도 낮아진다.
 *
 * 실행: `npm run seed:cache` (기본 프록시) 또는 `WORKER_URL=... npm run seed:cache`.
 * 규율: **curl 인라인 금지** — Node fetch는 깨끗한 UTF-8을 보낸다(Windows Git Bash 한글 함정 회피).
 * **429(HTTP 오류)엔 재시도하지 않는다**(쿼터 증폭 방지, 2026-07-27 인시던트). fizzle만 1회 재시도,
 * 끝내 cast 못 얻으면 그 문장은 시드에서 뺀다.
 *
 * ⚠️ 프롬프트 버전이 바뀌면 반드시 재생성한다 — 시드는 생성 당시 버전으로 태깅되며,
 * 클라의 `seedJudgeCache`는 현재 버전과 다르면 주입하지 않는다(스테일 방지).
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { JUDGE_PROMPT_VERSION, JUDGE_SCHEMA_VERSION } from '../src/spell/geminiJudge';
import { DEMO_SAMPLE_INCANTATIONS } from '../src/run/demoLoadout';

const WORKER_URL =
  process.env.WORKER_URL || 'https://incant-judge-proxy.diawodbsdot.workers.dev';
const ORIGIN = 'https://jaepaly.github.io';

// 심사위원이 즉흥으로 칠 법한 기본형 자유 영창 몇 종 (입구 예시 다음으로 흔한 입력).
// R1 쇼케이스 30종은 일부러 뺐다 — 심사위원이 실제 보는 건 입구 예시지 R1 이름이 아니고,
// 코퍼스가 크면 프리워밍 재생성이 무료 쿼터(RPD)를 통째로 태운다(2026-07-27 실측).
const COMMON_SPELLS = [
  '거대한 화염구를 던진다', '얼음 화살을 쏜다', '번개로 적을 감전시킨다',
  '빛의 방패로 나를 지킨다', '회오리바람을 일으킨다',
];

// 시연 입구 예시(심사위원이 처음 칠 확률 최상) → 흔한 기본형. 중복 제거·순서 보존.
const CORPUS = [...new Set([...DEMO_SAMPLE_INCANTATIONS, ...COMMON_SPELLS])];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function judgeOnce(text: string): Promise<Record<string, unknown> | null> {
  const res = await fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Origin: ORIGIN },
    body: JSON.stringify({ text }),
  });
  if (!res.ok) return null;
  return (await res.json()) as Record<string, unknown>;
}

/**
 * cast/blocked를 얻으면 반환. 못 얻으면 null(그 문장은 시드에서 뺀다).
 *
 * ⚠️ **HTTP 오류(429/upstream)엔 재시도하지 않는다** — 429는 "요청이 몰렸다"는 신호라
 * 재시도하면 **공용 프로젝트 쿼터를 더 태우며 상황을 악화**시킨다. 문장당 6회 재시도가
 * 2026-07-27 인시던트(무료 쿼터 순간 초과 → 팀 전체 Mock 폴백)의 증폭 원인이었다.
 * 자세한 건 docs/INCIDENT_2026-07-27_gemini-quota-429.md.
 *
 * fizzle(응답은 왔으나 nonsense)만 transient일 수 있어 **짧게 1회** 재시도한다(총 2시도).
 */
async function judgeWithRetry(text: string): Promise<Record<string, unknown> | null> {
  for (let attempt = 1; attempt <= 2; attempt += 1) {
    try {
      const j = await judgeOnce(text);
      if (j === null) {
        // HTTP 오류(429 등) — 재시도 금지(쿼터 증폭 방지). 이 문장은 건너뛴다.
        process.stdout.write(`  · "${text}" HTTP 오류(429?) → 재시도 안 함, 건너뜀\n`);
        return null;
      }
      const disposition = j.disposition;
      if (disposition === 'cast' || disposition === 'blocked') return j;
      process.stdout.write(`  · "${text}" ${String(disposition)} (fizzle 재시도 ${attempt}/2)\n`);
    } catch (err) {
      process.stdout.write(`  · "${text}" 예외 → 건너뜀: ${String(err)}\n`);
      return null;
    }
    await sleep(5000);
  }
  return null;
}

async function main(): Promise<void> {
  console.log(`캐시 시드 생성 — 버전 ${JUDGE_PROMPT_VERSION} · ${CORPUS.length}문장 · ${WORKER_URL}`);
  const entries: Record<string, unknown> = {};
  const skipped: string[] = [];
  for (const text of CORPUS) {
    const judgement = await judgeWithRetry(text);
    if (judgement) {
      entries[text] = judgement;
      const kind = judgement.spell_plan ? 'SEQ' : (judgement.disposition === 'cast' ? '단일' : String(judgement.disposition));
      console.log(`✅ ${text} → ${kind}`);
    } else {
      skipped.push(text);
      console.log(`⏭️  ${text} → cast 못 얻음, 건너뜀`);
    }
    await sleep(4500);
  }

  const seed = { version: JUDGE_PROMPT_VERSION, schema: JUDGE_SCHEMA_VERSION, entries };
  const banner =
    '// AUTO-GENERATED by scripts/generate-cache-seed.ts — 손으로 편집하지 말 것.\n'
    + `// 프롬프트 버전 바뀌면 재생성: npm run seed:cache\n`
    + `// 생성 버전: ${JUDGE_PROMPT_VERSION} · 항목 ${Object.keys(entries).length}/${CORPUS.length}\n`;
  const body =
    `${banner}import type { JudgeCacheSeed } from './geminiJudge';\n\n`
    + `export const CACHE_SEED: JudgeCacheSeed = ${JSON.stringify(seed, null, 2)};\n`;

  // npm run은 프로젝트 루트를 cwd로 설정한다. 번들 산출물 위치(node_modules/.cache)가
  // 아니라 cwd 기준으로 써야 src/에 정확히 떨어진다.
  const outPath = resolve(process.cwd(), 'src/spell/cacheSeed.generated.ts');
  writeFileSync(outPath, body, 'utf8');

  console.log(`\n완료 — ${Object.keys(entries).length}/${CORPUS.length} 시드. 건너뜀: ${skipped.length ? skipped.join(', ') : '없음'}`);
  console.log(`→ ${outPath}`);
}

await main();
